name: Release

permissions:
  # Attaching binary to release requires write perms
  contents: write

env:
  CARGO_FEATURE_SELECT: cli,polars

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi
    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        if (Get-Command "rustup" -ErrorAction SilentlyContinue) {
            rustup update
        } else {
            Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
            ./rustup-init.exe -y --profile minimal --default-toolchain stable
            echo ::add-path::%USERPROFILE%\.cargo\bin
        }

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Build release Win
      if: runner.os == 'Windows'
      run: cargo build --release --features $CARGO_FEATURE_SELECT

    - name: Build release Unix
      if: runner.os != 'Windows'
      run: cargo build --release --features $CARGO_FEATURE_SELECT
      env:
        RUSTFLAGS: '-C link-arg=-s'

    - name: Pack Unix
      if: runner.os != 'Windows'
      run: zip -j mishka-${{runner.os}}.zip target/release/mishka

    - name: Pack Windows
      if: runner.os == 'Windows'
      run: Compress-Archive -Path target/release/mishka.exe -Destination mishka-${{runner.os}}.zip

    - name: Upload to release Unix
      if: runner.os != 'Windows'
      run: |
        curl \
          -f \
          -sSL \
          -XPOST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --upload-file "mishka-${{runner.os}}.zip" \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=mishka-${{runner.os}}.zip"

    - name: Upload to release Windows
      if: runner.os == 'Windows'
      run: |
        $headers = @{"Authorization"="token ${{ secrets.GITHUB_TOKEN }}" };
        $event = Get-Content -Raw -Path $env:GITHUB_EVENT_PATH | ConvertFrom-Json;
        $url = "https://uploads.github.com/repos/$($env:GITHUB_REPOSITORY)/releases/$($event.release.id)/assets?name=mishka-${{runner.os}}.zip";
        Invoke-WebRequest -Headers $headers -Method POST -Infile mishka-${{runner.os}}.zip -ContentType 'application/zip' -Uri $url

  cross-linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Install cross
      run: cargo install cross

    - name: Build release
      run: cross build --release --target ${{matrix.target}} --features $CARGO_FEATURE_SELECT
      env:
        RUSTFLAGS: '-C link-arg=-s'

    - name: Pack
      run: zip -j mishka-${{matrix.target}}.zip target/${{matrix.target}}/release/mishka

    - name: Upload to release Unix
      run: |
        curl \
          -f \
          -sSL \
          -XPOST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --upload-file "mishka-${{matrix.target}}.zip" \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=mishka-${{matrix.target}}.zip"

  cross-mac-build:
    runs-on: macos-13

    strategy:
      matrix:
        target: [aarch64-apple-darwin]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Available SDK
      run: xcodebuild -showsdks

    - name: Install rust target
      run: rustup target add ${{matrix.target}}

    - name: Build release
      run: SDKROOT=$(xcrun -sdk macosx14.2 --show-sdk-path) MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx14.2 --show-sdk-platform-version)  cargo build --release --target ${{matrix.target}} --features $CARGO_FEATURE_SELECT
      env:
        RUSTFLAGS: '-C link-arg=-s'

    - name: Pack
      run: zip -j mishka-${{matrix.target}}.zip target/${{matrix.target}}/release/mishka

    - name: Upload to release Unix
      run: |
        curl \
          -f \
          -sSL \
          -XPOST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --upload-file "mishka-${{matrix.target}}.zip" \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=mishka-${{matrix.target}}.zip"
